/*
 * This file was generated by LibCSS gen_parser 
 * 
 * Generated from:
 *
 * shape_rendering:CSS_PROP_SHAPE_RENDERING IDENT:( INHERIT: AUTO:0,SHAPE_RENDERING_AUTO OPTIMIZESPEED:0,SHAPE_RENDERING_OPTIMIZESPEED CRISPEDGES:0,SHAPE_RENDERING_CRISPEDGES GEOMETRICPRECISION:0,SHAPE_RENDERING_GEOMETRICPRECISION DEFAULT:0,SHAPE_RENDERING_DEFAULT IDENT:)
 * 
 * Copyright (C) 2021 Beijing FMSoft Technologies Co., Ltd.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

/**
 * Parse shape_rendering
 *
 * \param c	  Parsing context
 * \param vector  Vector of tokens to process
 * \param ctx	  Pointer to vector iteration context
 * \param result  resulting style
 * \return CSS_OK on success,
 *	   CSS_NOMEM on memory exhaustion,
 *	   CSS_INVALID if the input is not valid
 *
 * Post condition: \a *ctx is updated with the next token to process
 *		   If the input is invalid, then \a *ctx remains unchanged.
 */
css_error css__parse_shape_rendering(css_language *c,
		const parserutils_vector *vector, int *ctx,
		css_style *result)
{
	int orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;

	token = parserutils_vector_iterate(vector, ctx);
	if ((token == NULL) || ((token->type != CSS_TOKEN_IDENT))) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((lwc_string_caseless_isequal(token->idata, c->strings[INHERIT], &match) == lwc_error_ok && match)) {
			error = css_stylesheet_style_inherit(result, CSS_PROP_SHAPE_RENDERING);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[AUTO], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_SHAPE_RENDERING, 0,SHAPE_RENDERING_AUTO);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[OPTIMIZESPEED], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_SHAPE_RENDERING, 0,SHAPE_RENDERING_OPTIMIZESPEED);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[CRISPEDGES], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_SHAPE_RENDERING, 0,SHAPE_RENDERING_CRISPEDGES);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[GEOMETRICPRECISION], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_SHAPE_RENDERING, 0,SHAPE_RENDERING_GEOMETRICPRECISION);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[DEFAULT], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_SHAPE_RENDERING, 0,SHAPE_RENDERING_DEFAULT);
	} else {
		error = CSS_INVALID;
	}

	if (error != CSS_OK)
		*ctx = orig_ctx;
	
	return error;
}

