/*
 * This file was generated by LibCSS gen_parser 
 * 
 * Generated from:
 *
 * stroke_linejoin:CSS_PROP_STROKE_LINEJOIN IDENT:( INHERIT: MITER:0,STROKE_LINEJOIN_MITER ROUND:0,STROKE_LINEJOIN_ROUND BEVEL:0,STROKE_LINEJOIN_BEVEL IDENT:)
 * 
 * Copyright (C) 2021 Beijing FMSoft Technologies Co., Ltd.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

/**
 * Parse stroke_linejoin
 *
 * \param c	  Parsing context
 * \param vector  Vector of tokens to process
 * \param ctx	  Pointer to vector iteration context
 * \param result  resulting style
 * \return CSS_OK on success,
 *	   CSS_NOMEM on memory exhaustion,
 *	   CSS_INVALID if the input is not valid
 *
 * Post condition: \a *ctx is updated with the next token to process
 *		   If the input is invalid, then \a *ctx remains unchanged.
 */
css_error css__parse_stroke_linejoin(css_language *c,
		const parserutils_vector *vector, int *ctx,
		css_style *result)
{
	int orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;

	token = parserutils_vector_iterate(vector, ctx);
	if ((token == NULL) || ((token->type != CSS_TOKEN_IDENT))) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((lwc_string_caseless_isequal(token->idata, c->strings[INHERIT], &match) == lwc_error_ok && match)) {
			error = css_stylesheet_style_inherit(result, CSS_PROP_STROKE_LINEJOIN);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[MITER], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_STROKE_LINEJOIN, 0,STROKE_LINEJOIN_MITER);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[ROUND], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_STROKE_LINEJOIN, 0,STROKE_LINEJOIN_ROUND);
	} else if ((lwc_string_caseless_isequal(token->idata, c->strings[BEVEL], &match) == lwc_error_ok && match)) {
			error = css__stylesheet_style_appendOPV(result, CSS_PROP_STROKE_LINEJOIN, 0,STROKE_LINEJOIN_BEVEL);
	} else {
		error = CSS_INVALID;
	}

	if (error != CSS_OK)
		*ctx = orig_ctx;
	
	return error;
}

