#!/bin/bash

gcc code-tools/css_property_parser_gen.c  -o gen_parser


cat code-tools/prop.gen | grep -v "^#" | grep -v "^$" | while read line
do
    prop=`echo $line | cut -d: -f1`
    ./gen_parser -o src/css/libcss/src/parse/properties/autogenerated_$prop.c "$line"
done

rm -f gen_parser
